<?
arch_add_info( 'theme', 'default' );
arch_add_info( 'base_url', 'http://www.andrewtrivette.com/archive/framework/' );
arch_add_info( 'data', 'flat' );
// Alternate data access. Yet to be implemented!
//arch_add_info( 'data', 'database' );
//arch_add_info( 'db_host', 'localhost' );
//arch_add_info( 'db_name', 'test' );
//arch_add_info( 'db_user', 'user' );
//arch_add_info( 'db_pass', 'pass' );
?>
