<?
arch_add_info( 'theme', 'default' );
arch_add_info( 'base_url', 'http://localhost/architect/' );
arch_add_info('title', 'ArchitectCMS');
arch_add_info('company', 'ArchitectCMS');
arch_add_info('description', 'ArchitectCMS is a remote content management system designed and provided by Andrew Trivette Design');
arch_add_info('email', 'andrew.trivette@gmail.com');
arch_add_info('ganalytics', 'UA-1097544-');
arch_add_info('year', '2007');
arch_add_info( 'data', 'flat' );
// Alternate data access. Yet to be implemented!
//arch_add_info( 'data', 'database' );
//arch_add_info( 'db_host', 'localhost' );
//arch_add_info( 'db_name', 'test' );
//arch_add_info( 'db_user', 'user' );
//arch_add_info( 'db_pass', 'pass' );
?>
